In [16]:
# Import necessary libraries
import numpy as np

# Load the data from the .npy file
data = np.load(
    '/home/juma/code/StrongSORT/results/StrongSORT_Git/MOT17_val_YOLOX+BoT/MOT17-02-FRCNN.npy', allow_pickle=True)

# Check the type of the loaded data
print("Type of the loaded data:", type(data))

# Check the shape of the data (if it's a numpy array)
if isinstance(data, np.ndarray):
    print("Shape of the loaded numpy array:", data.shape)

# If the loaded data is a dictionary, print its keys
elif isinstance(data, dict):
    print("Keys in the loaded dictionary:", data.keys())

# Display the first few items (for visualization purposes)
print("\nSample data:")
print(data[:10] if isinstance(data, np.ndarray) else {
      key: data[key] for key in list(data.keys())[:10]})

Type of the loaded data: <class 'numpy.ndarray'>
Shape of the loaded numpy array: (6931, 2058)

Sample data:
[[ 3.02000000e+02 -1.00000000e+00  8.89650000e+02 ...  5.06629825e-01
  -2.25781053e-01 -5.48850894e-01]
 [ 3.02000000e+02 -1.00000000e+00  5.95010000e+02 ...  5.54671228e-01
  -3.52803618e-01  7.70966411e-01]
 [ 3.02000000e+02 -1.00000000e+00  5.08610000e+02 ...  9.22136307e-01
   2.24458352e-01  5.75446077e-02]
 ...
 [ 3.02000000e+02 -1.00000000e+00  1.17180000e+03 ...  1.16458368e+00
  -4.57404017e-01  1.50411296e+00]
 [ 3.02000000e+02 -1.00000000e+00  1.02533000e+03 ...  9.15453553e-01
  -3.95188093e-01 -4.97130811e-01]
 [ 3.02000000e+02 -1.00000000e+00  5.98730000e+02 ...  5.06024718e-01
  -4.35240775e-01  8.52094233e-01]]


In [7]:
data[0, :10]

array([302.  ,  -1.  , 889.65, 422.55, 137.7 , 520.43,   0.94,  -1.  ,
        -1.  ,  -1.  ])

In [23]:
import numpy as np


def parse_detections(detection_mat, frame_idx, min_height=0):
    """Parse detections for given frame index from the raw detection matrix.

    Parameters
    ----------
    detection_mat : ndarray
        Matrix of detections. The first 10 columns of the detection matrix are
        in the standard MOTChallenge detection format. The next 128 columns are apperance features
    frame_idx : int
        The frame index.
    min_height : Optional[int]
        A minimum detection bounding box height. Detections that are smaller
        than this value are disregarded.

    Returns
    -------
    List[tuple]
        Returns parsed detections at the given frame index as a list of tuples.

    """
    frame_indices = detection_mat[:, 0].astype(int)
    mask = frame_indices == frame_idx

    parsed_detections = []
    for row in detection_mat[mask]:
        bbox, confidence = row[2:6], row[6]
        if bbox[3] < min_height:
            continue
        parsed_detections.append((bbox, confidence))
    return parsed_detections


# Example usage
data = np.load(
    '/home/juma/code/StrongSORT/results/StrongSORT_Git/MOT17_val_YOLOX+simpleCNN/MOT17-02-FRCNN.npy', allow_pickle=True)
frame_detections = parse_detections(data, frame_idx=302)
print(frame_detections)

[(array([     889.65,      422.55,       137.7,      520.43]), 0.94), (array([     1090.8,      489.38,        37.8,       102.6]), 0.48), (array([     1078.7,      487.69,       36.45,        94.5]), 0.35), (array([     1062.5,      485.66,       39.15,        97.2]), 0.35), (array([     552.15,      456.98,       19.58,       56.02]), 0.35), (array([     659.14,      456.64,       22.95,        59.4]), 0.31), (array([       1055,      485.66,        40.5,       99.23]), 0.3), (array([     1086.8,       488.7,       39.15,      114.75]), 0.3), (array([     561.94,      454.28,       20.93,        59.4]), 0.29), (array([    -177.69,      368.55,      294.98,      498.82]), 0.28), (array([     1035.5,      454.95,       33.75,        86.4]), 0.23), (array([     1089.5,      449.21,       33.75,        86.4]), 0.19), (array([     493.43,       461.7,       20.25,       56.03]), 0.19), (array([     1033.4,      449.55,        32.4,        83.7]), 0.18), (array([     490.73,      461.03,  

In [28]:
data.shape

(16573, 138)

In [30]:
data[0, 10:]

array([    0.20252,   -0.087769,     -0.1309,    -0.16093,    0.044612,     0.15892,     -0.1091,    -0.02924,   -0.024865,   -0.016113,    -0.11972,    0.021332,    -0.10938,    -0.11113,   -0.037135,     0.13726,   -0.028006,   -0.042552,   -0.032754,   -0.068337,   -0.050832,  -0.0032784,  -0.0069842,    -0.10886,
          0.029816,   -0.078215,   -0.054307,      0.1244,    0.074452,   -0.047754,    0.063267,   -0.013193,    0.031094,   -0.024817,    0.026344,   -0.047329,    0.014015,    -0.10357,      0.2309,   0.0065925,    0.049872,   0.0051434,    0.054378,   -0.038514,   -0.042408,    0.043666,   -0.025124,    -0.13292,
         -0.098629,    0.092761,    -0.10321,    -0.07926,    0.037476,   -0.047975,    0.046145,     0.16469,    -0.15919,    -0.02612,    0.098978,   -0.099101,    0.091676,    0.092709,   -0.021218,    -0.12796,    0.081412,    0.044538,    0.025198,    0.098178,    -0.05663,   -0.012976,   -0.046209,   -0.018804,
           0.13947,   0.0058223,     0.1209

56

# Minimalsitic REID code


In [2]:
from __future__ import division, print_function, absolute_import
from ultralytics import YOLO

import os
import time

import cv2
import numpy as np

from application_util import preprocessing
from application_util import visualization
from deep_sort import nn_matching
from deep_sort.detection import Detection
from deep_sort.tracker import Tracker
from opts import opt

usage: ipykernel_launcher.py [-h] [--iou_only] [--BoT] [--ECC] [--NSA] [--EMA]
                             [--MC] [--woC] [--AFLink] [--GSI]
                             [--root_dataset ROOT_DATASET]
                             [--path_AFLink PATH_AFLINK] [--dir_save DIR_SAVE]
                             [--EMA_alpha EMA_ALPHA] [--MC_lambda MC_LAMBDA]
                             dataset mode
ipykernel_launcher.py: error: the following arguments are required: dataset, mode


SystemExit: 2

In [15]:
import cv2
from fastreid.config import get_cfg
from fastreid.engine import DefaultTrainer

import os
import cv2
from PIL import Image
import torch
from torchvision import transforms
from fastreid.config import get_cfg
from fastreid.engine import DefaultTrainer
from fastreid.utils.checkpoint import Checkpointer


def load_reid_model():
    cfg_path = '/home/juma/code/StrongSORT/fast-reid/configs/DukeMTMC/bagtricks_S50.yml'
    model_weights = 'checkpoints/FastReID/market_bot_R50.pth'

    cfg = get_cfg()
    cfg.merge_from_file(cfg_path)
    cfg.MODEL.BACKBONE.PRETRAIN = False
    cfg.MODEL.WEIGHTS = model_weights
    model = DefaultTrainer.build_model(cfg)
    model.eval()
    Checkpointer(model).load(cfg.MODEL.WEIGHTS)
    return model


def get_detections_and_features(image_path, yolo_model, reid_model):
    image = cv2.imread(image_path)

    # Get detections
    detections = yolo_model.predict(
        image, classes=[0], verbose=False, imgsz=1280)
    boxes = detections[0].boxes.data.cpu().numpy()

    # Extract re-ID features
    img_pil = Image.fromarray(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    appearance_features = extract_reid_features(reid_model, img_pil, boxes)

    return boxes, appearance_features


def extract_reid_features(reid_model, img, boxes):
    transform = transforms.Compose([
        transforms.Resize((256, 128)),
        transforms.ToTensor()
    ])

    features_list = []
    for box in boxes:
        x1, y1, x2, y2 = box[:4]
        crop = img.crop((x1, y1, x2, y2))
        tensor_crop = transform(crop).unsqueeze(0).cuda()
        feature = reid_model(tensor_crop).detach().cpu().numpy().squeeze()
        features_list.append(feature)

    return features_list


if __name__ == '__main__':
    image_path = "/home/juma/code/StrongSORT/datasets/MOT17/test/MOT17-01-DPM/img1/000001.jpg"

    yolo_model = YOLO("yolov8m.pt")
    reid_model = load_reid_model()

    boxes, features = get_detections_and_features(
        image_path, yolo_model, reid_model)
    # Now you have detection boxes and corresponding re-ID features.
    # You can proceed with tracking or other tasks.

Skip loading parameter 'backbone.layer1.0.downsample.1.weight' to the model due to incompatible shapes: (256,) in the checkpoint but (256, 64, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer2.0.downsample.1.weight' to the model due to incompatible shapes: (512,) in the checkpoint but (512, 256, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer3.0.downsample.1.weight' to the model due to incompatible shapes: (1024,) in the checkpoint but (1024, 512, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer4.0.downsample.1.weight' to the model due to incompatible shapes: (2048,) in the checkpoint but (2048, 1024, 1, 1) in the model! You might want to double check if this is expected.


In [13]:
features

[array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081007,   0.0043441], dtype=float32),
 array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081007,   0.0043375], dtype=float32),
 array([   0.032417,     0.19678,     0.11436, ...,    0.023515,   0.0081004,   0.0043384], dtype=float32),
 array([   0.032417,     0.19679,     0.11436, ...,    0.023515,   0.0081004,   0.0043353], dtype=float32),
 array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081006,   0.0043404], dtype=float32),
 array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081008,   0.0043403], dtype=float32),
 array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081008,   0.0043443], dtype=float32),
 array([   0.032417,     0.19679,     0.11435, ...,    0.023515,   0.0081005,   0.0043328], dtype=float32),
 array([   0.032417,     0.19679,     0.11436, ...,    0.023515,   0.0081007,    0.004338], dtype=float32),
 array([   0.032417,     0.1

In [14]:
features[0].shape

(2048,)

In [11]:
boxes

array([[     1744.2,      520.56,      1902.8,      693.79,     0.87139,           0],
       [     983.25,      460.59,      1057.2,      645.05,     0.84222,           0],
       [     763.15,      460.35,      810.16,      585.17,     0.81758,           0],
       [     721.59,      457.19,      764.84,      588.67,     0.76901,           0],
       [     1092.3,      501.54,      1169.1,       608.8,     0.76433,           0],
       [     1210.6,      452.61,      1284.8,      627.98,     0.76238,           0],
       [     1048.2,      498.69,      1127.5,      607.08,     0.73561,           0],
       [     464.44,      459.81,      511.35,      560.49,     0.73135,           0],
       [      903.1,      492.36,      950.95,      586.24,     0.71899,           0],
       [     229.06,      463.51,      255.02,      534.08,      0.6834,           0],
       [     1286.8,      463.31,      1336.1,      621.98,     0.67797,           0],
       [     671.82,       466.5,      695.

In [32]:
import os
import cv2
from pathlib import Path
import torch
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('/home/juma/code/StrongSORT')
from ultralytics import YOLO

def process_frames(folder_path, model):
    
    # Path to the MOT17 sequence frames
    img_folder = os.path.join(folder_path, 'img1')
    img_files = sorted([os.path.join(img_folder, img)
                       for img in os.listdir(img_folder)])

    # Create a results folder if it doesn't exist
    results_folder = os.path.join(folder_path, 'yolov8_detections')
    os.makedirs(results_folder, exist_ok=True)

    # Process each frame
    for img_path in img_files:
        image = cv2.imread(img_path)
        results = model.predict(image,classes=[0])  # Apply detection
        # results[0].boxes.boxes # contains standard yolo boxes as tensor([[1.3376e+03, 4.1875e+02, 1.4995e+03, 7.8562e+02, 8.4918e-01, 0.0000e+00],
        # results[0].appearance_features.shape  is torch.Size([7, 16])
        # complete the code to construct data matrix where each row is detection with 138 columns, first 10 are MOT style detections, next 128 are appearance features
        
        
# Load a model
model = YOLO("yolov8n.pt")  # Load a pretrained model (recommended for training)
# Path to the MOT17 dataset sequence
folder_path = '/home/juma/code/StrongSORT/datasets/MOT17/train/MOT17-02-FRCNN'
frame_results = process_frames(folder_path, model)
frame_results



0: 384x640 7 persons, 2.6ms
Speed: 2.5ms preprocess, 2.6ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
Initialize the Results class.


[ultralytics.yolo.engine.results.Results object with attributes:
 
 appearance_features: tensor([[ 1.5715e+00, -7.6372e-02,  1.5370e+00,  2.3871e+00,  6.5414e+00,  7.8678e-01,  4.3440e+00,  1.0033e+00,  2.6057e+00,  1.1148e+00,  5.2812e-02,  3.0144e+00,  1.6098e+00,  1.7079e+00, -9.6450e-03,  1.4520e+00],
         [ 2.5324e+00,  2.6941e-02,  1.3343e+00,  2.5282e+00,  6.5563e+00,  8.5382e-01,  4.6986e+00,  2.7309e-01,  3.3199e+00,  1.0985e+00,  3.2390e-02,  2.8007e+00,  2.1908e+00,  2.1265e+00,  3.0050e-01,  1.3927e+00],
         [ 1.6184e+00, -9.3901e-02,  1.4332e+00,  2.2188e+00,  6.7908e+00,  8.3455e-01,  4.5996e+00,  9.4680e-01,  2.4146e+00,  9.6656e-01,  3.7509e-02,  2.6725e+00,  1.5574e+00,  1.6084e+00, -4.8262e-02,  1.5523e+00],
         [ 1.9601e+00,  4.0577e-02,  1.1042e+00,  2.3256e+00,  6.5684e+00,  1.0101e+00,  4.5881e+00,  4.1724e-01,  3.2280e+00,  9.4004e-01,  2.9370e-02,  3.2162e+00,  1.6777e+00,  2.0890e+00,  2.3202e-01,  1.5426e+00],
         [ 1.4140e+00, -1.6221e-02, 

In [ ]:
from ultralytics import YOLO
import os
import cv2
from pathlib import Path
import torch
# %load_ext autoreload
# %autoreload 2
import sys
sys.path.append('/home/juma/code/StrongSORT')


def process_frames(folder_path, model):
    data_matrix = []

    # Path to the MOT17 sequence frames
    img_folder = os.path.join(folder_path, 'img1')
    img_files = sorted([os.path.join(img_folder, img)
                       for img in os.listdir(img_folder)])

    # Create a results folder if it doesn't exist
    results_folder = os.path.join(folder_path, 'yolov8_detections')
    os.makedirs(results_folder, exist_ok=True)

    # Process each frame
    for frame_number, img_path in enumerate(img_files, start=1):
        image = cv2.imread(img_path)
        # Apply detection for 'person' class
        results = model.predict(image, classes=[0])

        boxes = results[0].boxes.boxes.cpu().numpy()
        appearance_features = results[0].appearance_features.cpu().numpy()

        for box, feature in zip(boxes, appearance_features):
            # Constructing the MOT format
            left, top, right, bottom, conf, _ = box
            width = right - left
            height = bottom - top
            mot_format = [frame_number, -1, left,
                          top, width, height, conf, -1, -1, -1]

            # Combining MOT format with appearance features
            detection_data = mot_format + feature.tolist()
            data_matrix.append(detection_data)

    return data_matrix


# Load a model
# Load a pretrained model (recommended for training)
model = YOLO("yolov8n.pt")
# Path to the MOT17 dataset sequence
folder_path = '/home/juma/code/StrongSORT/datasets/MOT17/train/MOT17-02-FRCNN'
frame_results = process_frames(folder_path, model)
print(frame_results)

In [37]:
frame_results

[[1,
  -1,
  1337.5969,
  418.74582,
  161.86963,
  366.87076,
  0.84917694,
  -1,
  -1,
  -1,
  1.5715172290802002,
  -0.0763716846704483,
  1.5370094776153564,
  2.387117624282837,
  6.541410446166992,
  0.7867823839187622,
  4.344040870666504,
  1.0033153295516968,
  2.605712890625,
  1.114816427230835,
  0.05281202495098114,
  3.01444411277771,
  1.6097575426101685,
  1.7079294919967651,
  -0.009644962847232819,
  1.452028751373291],
 [1,
  -1,
  583.72754,
  447.523,
  90.843506,
  260.65448,
  0.83597785,
  -1,
  -1,
  -1,
  2.532350778579712,
  0.02694106660783291,
  1.3343077898025513,
  2.528226137161255,
  6.556253910064697,
  0.8538229465484619,
  4.698587894439697,
  0.2730901539325714,
  3.31992506980896,
  1.0984885692596436,
  0.03239023685455322,
  2.8007287979125977,
  2.1907780170440674,
  2.1264965534210205,
  0.300497442483902,
  1.3926832675933838],
 [1,
  -1,
  1457.2019,
  434.88153,
  138.27551,
  327.9322,
  0.76951784,
  -1,
  -1,
  -1,
  1.6184325218200684,
 

In [23]:
frame_results[0].boxes.shape

torch.Size([7, 6])

# FastREID


In [2]:
!pip install fastreid

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.8/247.8 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 11.0 MB/s eta 0:00:0000:0100:01
  Obtaining dependency information for opencv-python-headless<5.0.0.0,>=4.7.0.68 from https://files.pythonhosted.org/packages/9d/d7/e2aaf344254292d2046f9984b54212e4e7d69a57d30ae15e7294840710f6/opencv_python_headless-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for scikit-learn<2.0.0,>=1.2.1 from https://files.pythonhosted.org/packages/91/4e/752fd6e0b6b828a9cd815941fb70723eaef5d0f4efd8b9b0eee7864b3511/scikit_learn-1.3.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
  Obtaining dependency information for tensorboard<3.0.0,>=2.12.0 from https://files.pythonhosted.org/packages/bc/a2/ff5f4c299eb37c95299a76015da3f30211468e29d8d6f1d011683279baee/tensorboard-2.14.0-py3-none-any.whl.metad

In [14]:
import torch
from fastreid.config import get_cfg
from fastreid.engine import DefaultTrainer
from fastreid.utils.checkpoint import Checkpointer
from torchvision import transforms
from PIL import Image


def load_reid_model():
    cfg_path = '/home/juma/code/StrongSORT/fast-reid/configs/DukeMTMC/bagtricks_S50.yml'
    model_weights = 'checkpoints/FastReID/market_bot_R50.pth'

    cfg = get_cfg()
    cfg.merge_from_file(cfg_path)
    cfg.MODEL.BACKBONE.PRETRAIN = False
    cfg.MODEL.WEIGHTS = model_weights
    model = DefaultTrainer.build_model(cfg)
    model.eval()
    Checkpointer(model).load(cfg.MODEL.WEIGHTS)
    return model


def get_transform(size=(256, 128)):
    transform = transforms.Compose([
        transforms.Resize(size),
        transforms.ToTensor()
    ])
    return transform


def extract_reid_features(model, img, detections):
    transform = get_transform((256, 128))
    features_list = []

    for det in detections:
        crop = img.crop((det[2], det[3], det[2] + det[4], det[3] + det[5]))
        tensor_crop = transform(crop).unsqueeze(0).cuda()
        feature = model(tensor_crop).detach().cpu().numpy()
        features_list.append(feature)

    return features_list


if __name__ == '__main__':
    # Configuration paths

    # Load model and extract features
    reid_model = load_reid_model()

    # Load your image and bounding boxes here
    img_path = 'sample_image.jpg'
    img = Image.open(img_path)
    # For demonstration purpose, using dummy detections. Replace this with your YOLOv8 detections
    detections = [[0, 0, 50, 50, 150, 150], [0, 0, 100, 100, 250, 250]]

    features = extract_reid_features(reid_model, img, detections)

Skip loading parameter 'backbone.layer1.0.downsample.1.weight' to the model due to incompatible shapes: (256,) in the checkpoint but (256, 64, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer2.0.downsample.1.weight' to the model due to incompatible shapes: (512,) in the checkpoint but (512, 256, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer3.0.downsample.1.weight' to the model due to incompatible shapes: (1024,) in the checkpoint but (1024, 512, 1, 1) in the model! You might want to double check if this is expected.
Skip loading parameter 'backbone.layer4.0.downsample.1.weight' to the model due to incompatible shapes: (2048,) in the checkpoint but (2048, 1024, 1, 1) in the model! You might want to double check if this is expected.


## use pytorch_deepsort

- https://github.com/ZQPei/deep_sort_pytorch


In [12]:

class BasicBlock(nn.Module):
    def __init__(self, c_in, c_out, is_downsample=False):
        super(BasicBlock, self).__init__()
        self.is_downsample = is_downsample
        if is_downsample:
            self.conv1 = nn.Conv2d(
                c_in, c_out, 3, stride=2, padding=1, bias=False)
        else:
            self.conv1 = nn.Conv2d(
                c_in, c_out, 3, stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(c_out)
        self.relu = nn.ReLU(True)
        self.conv2 = nn.Conv2d(c_out, c_out, 3, stride=1,
                               padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(c_out)
        if is_downsample:
            self.downsample = nn.Sequential(
                nn.Conv2d(c_in, c_out, 1, stride=2, bias=False),
                nn.BatchNorm2d(c_out)
            )
        elif c_in != c_out:
            self.downsample = nn.Sequential(
                nn.Conv2d(c_in, c_out, 1, stride=1, bias=False),
                nn.BatchNorm2d(c_out)
            )
            self.is_downsample = True

    def forward(self, x):
        y = self.conv1(x)
        y = self.bn1(y)
        y = self.relu(y)
        y = self.conv2(y)
        y = self.bn2(y)
        if self.is_downsample:
            x = self.downsample(x)
        return F.relu(x.add(y), True)


def make_layers(c_in, c_out, repeat_times, is_downsample=False):
    blocks = []
    for i in range(repeat_times):
        if i == 0:
            blocks += [BasicBlock(c_in, c_out, is_downsample=is_downsample),]
        else:
            blocks += [BasicBlock(c_out, c_out),]
    return nn.Sequential(*blocks)


class Net(nn.Module):
    def __init__(self, num_classes=625, reid=False):
        super(Net, self).__init__()
        # 3 128 64
        self.conv = nn.Sequential(
            nn.Conv2d(3, 32, 3, stride=1, padding=1),
            nn.BatchNorm2d(32),
            nn.ELU(inplace=True),
            nn.Conv2d(32, 32, 3, stride=1, padding=1),
            nn.BatchNorm2d(32),
            nn.ELU(inplace=True),
            nn.MaxPool2d(3, 2, padding=1),
        )
        # 32 64 32
        self.layer1 = make_layers(32, 32, 2, False)
        # 32 64 32
        self.layer2 = make_layers(32, 64, 2, True)
        # 64 32 16
        self.layer3 = make_layers(64, 128, 2, True)
        # 128 16 8
        self.dense = nn.Sequential(
            nn.Dropout(p=0.6),
            nn.Linear(128*16*8, 128),
            nn.BatchNorm1d(128),
            nn.ELU(inplace=True)
        )
        # 256 1 1
        self.reid = reid
        self.batch_norm = nn.BatchNorm1d(128)
        self.classifier = nn.Sequential(
            nn.Linear(128, num_classes),
        )

    def forward(self, x):
        x = self.conv(x)
        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)

        x = x.view(x.size(0), -1)
        if self.reid:
            x = self.dense[0](x)
            x = self.dense[1](x)
            x = x.div(x.norm(p=2, dim=1, keepdim=True))
            return x
        x = self.dense(x)
        # B x 128
        # classifier
        x = self.classifier(x)
        return x

In [15]:
import torch
import torchvision.transforms as transforms
import numpy as np
import cv2
import logging


from fastreid.config import get_cfg
from fastreid.engine import DefaultTrainer
from fastreid.utils.checkpoint import Checkpointer


class Extractor(object):
    def __init__(self, model_path, use_cuda=True):
        self.net = Net(reid=True)
        self.device = "cuda" if torch.cuda.is_available() and use_cuda else "cpu"
        state_dict = torch.load(model_path, map_location=lambda storage, loc: storage)[
            'net_dict']
        self.net.load_state_dict(state_dict)
        logger = logging.getLogger("root.tracker")
        logger.info("Loading weights from {}... Done!".format(model_path))
        print("Loading weights from {}... Done!".format(model_path))
        self.net.to(self.device)
        self.size = (64, 128)
        self.norm = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
        ])

    def _preprocess(self, im_crops):
        """
        TODO:
            1. to float with scale from 0 to 1
            2. resize to (64, 128) as Market1501 dataset did
            3. concatenate to a numpy array
            3. to torch Tensor
            4. normalize
        """
        def _resize(im, size):
            return cv2.resize(im.astype(np.float32)/255., size)

        im_batch = torch.cat([self.norm(_resize(im, self.size)).unsqueeze(
            0) for im in im_crops], dim=0).float()
        return im_batch

    def __call__(self, im_crops):
        im_batch = self._preprocess(im_crops)
        with torch.no_grad():
            im_batch = im_batch.to(self.device)
            features = self.net(im_batch)
        return features.cpu().numpy()


img = cv2.imread("sample_image.jpg")

img = img[:, :, (2, 1, 0)]
extr = Extractor(
    "/home/juma/code/StrongSORT/checkpoints/FastReID/deepsort/original_ckpt.t7")


feature = extr([img])
print(feature.shape)

Loading weights from /home/juma/code/StrongSORT/checkpoints/FastReID/deepsort/original_ckpt.t7... Done!
(1, 128)


In [1]:
import torch
import torchvision.transforms as transforms
from PIL import Image
from deep_sort.deep.feature_extractor import Extractor


def extract_features(image_path, model_path):
    # Load pre-trained model for feature extraction
    model = Extractor(model_path)

    # Open the image and prepare it for processing
    img = Image.open(image_path).convert('RGB')

    # The repository uses this transform for preprocessing
    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[
                             0.229, 0.224, 0.225])
    ])

    # Apply transformations and add batch dimension
    img_tensor = transform(img).unsqueeze(0)

    # Extract appearance features
    with torch.no_grad():
        features = model(img_tensor)

    return features


# Example usage
# Change this to the path of the model checkpoint
model_path = "path_to_deepsort_model_checkpoint.ckpt"
image_path = "example.jpg"
features = extract_features(image_path, model_path)
print(features)

/home/juma/code/StrongSORT/myenv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


ModuleNotFoundError: No module named 'deep_sort.deep'

In [12]:
features[1].shape

(1, 2048)